spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/vollmed_api
    username: root
    password: 10482285
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update